### ISSUE TITLE
Some important questions

### ISSUE THREAD

**Issue by gelsas** [b0bh00d/Reactor#1]
Hi,

Question 1:
I have never used GO before but this application seems to do exactly what I need. It just perfectly describes what I need!
Would it be possible that you could create an already compiled version of this? If that is not possible could you guide a "noob/beginner" like me on how to get it setup myself?

Question 2:
Is it possible to add a Backup solution to this so whenever something is synced if there was a change in a file that that file gets backed up to an archive folder and then replaced? (I think the rclone command for that is something like this: --backup-dir "gcrypt:shared/Archive/"date -I/date +%HH%MM`)
Or does Reactor does this already? ("Reactor is really designed to handle incremental updates to existing synchornized data.")

Hope it is okay that a total beginner like me is asking these "stupid" questions.

best,
gelsas

**Comment by b0bh00d** [comment]
No worries.  Reactor was only my second Go project, so I'm sure there are still depths to the language I have yet to fathom myself.

I'll add my latest Windows build (produced with go version 1.16.7) as a release for you to grab.  If you follow the instructions in the README.md _precisely_ (I recently switched to a new machine, and had to do so myself), things should work.

I would try it out with a small collection of files first until you are sure everything is working as expected.  Then remember to make sure you set up the environment completely with rclone before pointing Reactor at it.

**Comment by gelsas** [comment]
Thank you will try it out in the next few hours when I am back at home again.

Really appreciate the quick response! 

Regarding my second question, from how I understand the text in the XML file I could add my extra rclone option: --backup-dir "gcrypt:shared/Archive/"date -I/date +%HH%MM` in the <options> </options> section, right ?

```
          <!--
            You can add rclone options that will be specific to this remote or the files in this watchpoint.
            Be careful which options you provide; Reactor uses its own in order to function, so you need to
            take pains not to duplicate (and thus, override) them here.
          -->
          <options>--drive-use-trash=false --exclude ._sync_*</options>
```

**Comment by b0bh00d** [comment]
From the sample XML file:

>             You can add rclone options that will be specific to this remote or the files in this watchpoint.
>             Be careful which options you provide; Reactor uses its own in order to function, so you need to
>             take pains not to duplicate (and thus, override) them here.

From my log output, the rclone command line looks like this:

&nbsp;&nbsp;rclone sync --log-file=&lt;logfile&gt; --log-level INFO _**--drive-use-trash=false --exclude ._sync_***_ &lt;path to sync&gt;  psecret:&lt;path to sync&gt;

The middle section of the command above that is bolded/italicized is taken from the XML file.  Everything else is added by Reactor.  The "&lt;path to sync&gt;" is identicial--this means the local path containing the file-system event is an exact mirror of the path on the cloud-storage target.  So, if I'm watching "Y:/Nextcloud" and I have an event in "Nextcloud/Shell/Windows/Cmder/config", then Reactor will point rclone at that local path, and give it _the exact same path_ on the cloud target to syncrhonize.  So, a full rclone command emitted and run by Reactor might look like:

&nbsp;&nbsp;rclone sync --log-file=&lt;logfile&gt; --log-level INFO _**--drive-use-trash=false --exclude ._sync_***_  Nextcloud/Shell/Windows/Cmder/config psecret:Nextcloud/Shell/Windows/Cmder/config

I'm not familiar with the purpose/use of rclone's "backup-dir" option, but if it does not interfere with Reactor's design (that of exactly mirroring from local to cloud), then I would say you would be safe placing it into the XML so it could be inserted into the rclone command.  However, if you are attempting to specify a target location on the cloud storage, it will interfere with the operation (and intent) of Reactor, and I could pretty much guarantee failure and some nasty messages (at best; at worst, you might risk your files).

**Comment by gelsas** [comment]
Hi!

I do have one more beginner question. Up until now I had used a software called BestSync but I want to fully switch to Reactor now. I just switched about a few weeks ago to rclone and now I want to create the perfect setup with it so everything gets handled by rclone through reactor (if that is possible).

Could you help me figure out how best to achieve this with Reactor and its settings. 

In BestSync I had the following setup:

Task 1:
At Windows Start up do a two way sync between C:\Data and (a network share/ftp connection) X:\SyncFolder\Data

After Task 1 is finished start Task 2:
One way Live sync (at every file change) from local storage C:\Data to networkshare  X:\SyncFolder\Data. 

Task 3:
One way sync every 30 mintues from C:\Data to different network share Z:\OffSideSyncFolder\Data

Task 4: 
Two way Live sync from local storage D:\Share to networkshare X:\SyncFolder\Share.

Task 5: 
Two way Live sync from local storage D:\Photos to networkshare X:\SyncFolder\Photos.

____________

Can the above be automated via Reactor?

In addition to the different tasks above I want to add a continuous/live sync of the following folders 
C:\Data
D:\Share
D:\Photos

to google drive remote: 
gcrypt:/shared/Username/SyncFolder/Data
gcrypt:/shared/Username/SyncFolder/Share
gcrypt:/shared/Username/SyncFolder/Photos

How do i need to specify the google drive "task" to work correctly in Reactor?

I hope its okay that I ask in this much detail, I just want to be sure to correctly set everything up.
